name: tests

concurrency:
    group: phpunit-tests-${{ github.ref_name }}
    cancel-in-progress: true

on: ['push', 'pull_request', 'workflow_dispatch']

env:
    ELASTICSEARCH_PORT: 9205

jobs:
    static_code_analysis:
        runs-on: 'ubuntu-24.04'
        name: 'Static code analysis'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'

            - name: Checkout
              uses: actions/checkout@v4

            - name: 'Validate composer.json and composer.lock'
              run: composer validate

            - name: 'Install dependencies with Composer'
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: 'highest'
                  composer-options: '--prefer-dist'

            - name: Check PHP coding standards
              run: php vendor/bin/php-cs-fixer fix --verbose --dry-run

    phpunit:
        needs: [ static_code_analysis ]
        runs-on: 'ubuntu-24.04'
        name: 'PHPUnit (PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, ES ${{ matrix.elasticsearch }})'
        timeout-minutes: 30
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            matrix:
                experimental:
                    - false
                dependencies:
                    - 'highest'
                php:
                    - '8.3'
                    - '8.4'
                elasticsearch:
                    - '9.3.2'
                symfony:
                    - '~6.0'
                include:
                    # Oldest supported ES9 server
                    - php: '8.3'
                      symfony: '~6.0'
                      elasticsearch: '9.0.0'
                      experimental: false
                    # Symfony 7
                    - php: '8.3'
                      symfony: '~7.0'
                      elasticsearch: '9.3.2'
                      experimental: false
                    - php: '8.4'
                      symfony: '~7.0'
                      elasticsearch: '9.3.2'
                      experimental: false
                    # Symfony 8
                    - php: '8.4'
                      symfony: '~8.0'
                      elasticsearch: '9.3.2'
                      experimental: false
            fail-fast: false
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '${{ matrix.php }}'
                  coverage: 'pcov'
                  tools: 'composer:v2'
                  extensions: 'curl, json, mbstring, openssl'
                  ini-values: 'memory_limit=256M'

            - name: 'Fix symfony/framework-bundle version'
              run: composer require --no-update symfony/framework-bundle:'${{ matrix.symfony }}'

            - name: 'Install dependencies with Composer'
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: '${{ matrix.dependencies }}'
                  composer-options: '--prefer-dist'

            - name: 'Dump composer autoloader'
              run: composer dump-autoload --classmap-authoritative --no-ansi --no-interaction --no-scripts

            - name: 'Setup Elasticsearch'
              env:
                  ELASTICSEARCH_VERSION: ${{ matrix.elasticsearch }}
              run: |
                  if ! docker compose up --detach --wait; then
                      echo '::group::Elasticsearch container logs'
                      docker compose logs elasticsearch
                      echo '::endgroup::'
                      exit 1
                  fi
                  curl -XGET 'http://localhost:'"$ELASTICSEARCH_PORT"

            - name: 'Run phpunit tests'
              run: |
                  vendor/bin/phpunit --coverage-clover=tests/App/build/clover.xml

            - name: Upload coverage results to Coveralls
              uses: coverallsapp/github-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  file: tests/App/build/clover.xml
                  parallel: true

            # Enable tmate debugging on failure for 15 minutes
            - name: Setup tmate session
              if: ${{ !env.ACT && failure() }}
              uses: mxschmitt/action-tmate@v3
              timeout-minutes: 15

    finalize:
        needs: [phpunit]
        runs-on: ubuntu-24.04
        steps:
            - name: Finalize Coveralls Parallel Build
              uses: coverallsapp/github-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel-finished: true

